const AnimationScrollError = () => {
    return (

        <div className="textConteiner primary">
            <div className='textScrollAnimation'>ERROR</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>404</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>ERREUR</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>KLAIDA</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>NOT FOUND</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>ERROR</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>404</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>ERREUR</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>KLAIDA</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>NOT FOUND</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>ERROR</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>404</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>ERREUR</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>KLAIDA</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>NOT FOUND</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>ERROR</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>404</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>ERREUR</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>KLAIDA</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>NOT FOUND</div>
            <div className="ScrollAnimationDivider"></div>

            <div className='textScrollAnimation'>ERROR</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>404</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>ERREUR</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>KLAIDA</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>NOT FOUND</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>ERROR</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>404</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>ERREUR</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>KLAIDA</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>NOT FOUND</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>ERROR</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>404</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>ERREUR</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>KLAIDA</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>NOT FOUND</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>ERROR</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>404</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>ERREUR</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>KLAIDA</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>NOT FOUND</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>ERROR</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>404</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>ERREUR</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>KLAIDA</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>NOT FOUND</div>
            <div className="ScrollAnimationDivider"></div>

            <div className='textScrollAnimation'>ERROR</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>404</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>ERREUR</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>KLAIDA</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>NOT FOUND</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>ERROR</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>404</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>ERREUR</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>KLAIDA</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>NOT FOUND</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>ERROR</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>404</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>ERREUR</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>KLAIDA</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>NOT FOUND</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>ERROR</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>404</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>ERREUR</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>KLAIDA</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>NOT FOUND</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>ERROR</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>404</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>ERREUR</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>KLAIDA</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>NOT FOUND</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>ERROR</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>404</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>ERREUR</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>KLAIDA</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>NOT FOUND</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>ERROR</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>404</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>ERREUR</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>KLAIDA</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>NOT FOUND</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>ERROR</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>404</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>ERREUR</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>KLAIDA</div>
            <div className="ScrollAnimationDivider"></div>
            <div className='textScrollAnimation'>NOT FOUND</div>
            <div className="ScrollAnimationDivider"></div>

        </div>

    )

}


export default AnimationScrollError